//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookcustomer
    {
        public int room_id { get; set; }
        public string NameCus { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> NgayStart { get; set; }
        public Nullable<System.DateTime> NgayEnd { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
