//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotels()
        {
            this.Images = new HashSet<Images>();
            this.rooms = new HashSet<rooms>();
        }
    
        public int hotel_id { get; set; }
        public int location_id { get; set; }
        public string hotel_name { get; set; }
        public string note { get; set; }
        public string hotel_gia { get; set; }
        public string hotel_review { get; set; }
        public string hotel_title { get; set; }
        public string hotel_rating { get; set; }
        public string hotel_image { get; set; }
    
        public virtual locations locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rooms> rooms { get; set; }
    }
}
