//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNTT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BigSchool_NhuHoangHaiEntities2 : DbContext
    {
        public BigSchool_NhuHoangHaiEntities2()
            : base("name=BigSchool_NhuHoangHaiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<bookcustomer> bookcustomer { get; set; }
        public virtual DbSet<hotels> hotels { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<sections> sections { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Testimonials> Testimonials { get; set; }
    }
}
