//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms
    {
        public int room_id { get; set; }
        public int hotel_id { get; set; }
        public Nullable<int> section_id { get; set; }
        public Nullable<int> sale_id { get; set; }
        public Nullable<int> floor { get; set; }
        public string gia { get; set; }
    
        public virtual sales sales { get; set; }
        public virtual sections sections { get; set; }
        public virtual hotels hotels { get; set; }
    }
}
