//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonials
    {
        public int test_id { get; set; }
        public string test_name { get; set; }
        public string test_ngay { get; set; }
        public string test_note { get; set; }
        public string test_image { get; set; }
        public string test_icon { get; set; }
    }
}
